platform :ios, '6.0'

pod 'FlatUIKit'
pod 'DB5'
pod 'SVProgressHUD'
pod 'AFNetworking', '~> 1.3.2'
pod 'NSString-Hashes'
pod 'SocketClient'
pod 'TBXML'
pod 'TBXML+NSDictionary'
pod 'AKSegmentedControl'
pod 'MJPopupViewController'
pod 'NSString-HTML'
pod 'SocketRocket'
pod 'iRate'
pod 'JSBadgeView'
pod 'RMSwipeTableViewCell'
