platform :ios, '6.0'

pod 'FlatUIKit'
pod 'FLKAutoLayout'
pod 'DB5'
pod 'SVProgressHUD'
#pod 'RestKit'
pod 'AFNetworking', '~> 1.3.2'
pod 'NSString-Hashes'
pod 'SocketClient'
pod 'MNPageViewController'
#pod 'XMLDictionary'
pod 'TBXML'
pod 'TBXML+NSDictionary'
pod 'AKSegmentedControl'
pod 'MJPopupViewController'
pod 'NSString-HTML'
